version: '3'
services:
  neo4j:
    container_name: ms_neo4j
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=none
    ports:
      - "7474:7474"
      - "7687:7687"

  apigateway:
    build: 
      context: ./APIGateway
    image: apigateway
    # volumes:
    #   - "./apigateway:/src/app"
    # working_dir: "/src/app"
    ports:
        - "4000:4000"